//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id_chat { get; set; }
        public Nullable<int> id_user { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
