//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.carts = new HashSet<cart>();
            this.order_item = new HashSet<order_item>();
        }
    
        public int id_product { get; set; }
        public string names { get; set; }
        public string images { get; set; }
        public Nullable<decimal> price { get; set; }
        public string display { get; set; }
        public string weights { get; set; }
        public string water_resistance { get; set; }
        public string operating_system { get; set; }
        public string processor { get; set; }
        public string battery { get; set; }
        public string ram { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> id_promo { get; set; }
        public string rom { get; set; }
        public string brand { get; set; }
        public string color { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual promocode promocode { get; set; }
    }
}
